table 'Headers - DTC'
	lineageTag: 9078dffa-286e-4a7e-8fac-d9f55e75ee62

	column Metric
		dataType: string
		lineageTag: 6d13f192-343a-4dd2-9483-c44a0038ce57
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 19d74cfa-67c2-466a-8a71-31cc1800f5b1
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: 'Period Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Metric Sort'
		dataType: int64
		formatString: 0
		lineageTag: 41d2805a-01ff-4919-9c72-63ea98a15989
		summarizeBy: sum
		sourceColumn: Metric Sort

		annotation SummarizationSetBy = Automatic

	column 'Period Sort'
		dataType: int64
		formatString: 0
		lineageTag: 8d31b0dd-d2bb-4937-a0c7-93a32986a910
		summarizeBy: sum
		sourceColumn: Period Sort

		annotation SummarizationSetBy = Automatic

	partition 'Headers - DTC' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rZfNasJAFIVfZRALFrrQJP4tJYF2YxV/Woq4GDTaUDuBTGy3XfRJ+yRNtcyN5cxkRgu6CZ7Dd04m98bFohbFr1ys2W2WSskmcc6THZvyXSxZvXZT+/r4LH8eZ9GfK8VvWofv8sbRa6jz8ty9nnRe/sHrPs4dM3kqk1ELM3gqg1ELmT3FHIU/qfeZUOnrrBEl2yTnOzbeZ6tnLuNryzgB3aIzbWHSgO7WmbawhECVMM3TLP7HHtqqhwucYRVtVcUFzrCNtqaNMJX5JV10NF04+MImOpomHHxhD53KU3G87tpDt/JMVPrCHrqVJ6LSF/bQVT0MefayTt8FqyvXRsgFX3Pb7D2V3ckL5u2pvE5eMGPvZHQfd0Dhuk2E9QTvn0zwKguYqH8yyKssYJC+PsiV7Xpt6ZMAD7xWW/oowAOvU9qns4xvNsnKNoCvAmiFmNpX1FohRvXLqELyVZ6kQtryBmVegxpDB2VogxqT0+4LU/EWZ7IQ23LTdjNpMTXtL5MWM9OGGowebGFp/UARpqTdAkUYjxbHXCS59SmgvaCRYUQa+xoZhqSpPh/PbBFpfEMRBqQ5DUUYjwbyYD6xxaMRDEUYj4YuFGE8GrO/bxkjwe6Kvw+WpF6z9OSY9fiNv1l6esx6/NbfPPIvvwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Period = _t, #"Metric Sort" = _t, #"Period Sort" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Period", type text}, {"Metric Sort", Int64.Type}, {"Period Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

