table Channel
	lineageTag: 4f88c5b9-e237-47bb-bae4-cbda8cab639e

	column 'Channel Key'
		dataType: double
		isHidden
		isKey
		isNullable: false
		formatString: 0
		sourceProviderType: decimal(38, 0)
		lineageTag: a9c433f4-6151-4b8f-a85c-8e1c813289ae
		summarizeBy: none
		sourceColumn: Channel Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Channel Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 0d250b92-50f4-4a1f-8a10-332c4f05c9a9
		summarizeBy: none
		sourceColumn: Channel Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sub Channel Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 243f2633-39ee-4708-8c7b-76ac12093307
		summarizeBy: none
		sourceColumn: Sub Channel Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Channel Format'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 7ee1194c-5494-4e4d-9813-b76508c91918
		summarizeBy: none
		sourceColumn: Channel Format

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Channel Geography'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: d49f1b6e-cd65-42dd-9f9e-b6d637325e2f
		summarizeBy: none
		sourceColumn: Channel Geography

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Channel Active'
		dataType: string
		isHidden
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 20c2af0b-a872-47f2-9ec7-6789d446d23b
		summarizeBy: none
		sourceColumn: Channel Active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Finance Channel'
		dataType: string
		lineageTag: 3ce1747c-394a-4c8b-ad87-1083b464ca22
		summarizeBy: none
		sourceColumn: Finance Channel
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f905bcb4-9eb5-4cb6-b6dc-83ddd314fe93
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column 'Finance Channel (Product Dashboard) Sort'
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 03b72c84-789a-4f6c-ac31-1c27298d8a44
		summarizeBy: sum
		sourceColumn: Finance Channel (Product Dashboard) Sort

		annotation SummarizationSetBy = Automatic

	column 'Finance Channel (Product Dashboard)'
		dataType: string
		lineageTag: 89302387-ff2a-4564-87af-90eaf6da8957
		summarizeBy: none
		sourceColumn: Finance Channel (Product Dashboard)
		sortByColumn: 'Finance Channel (Product Dashboard) Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Channel = m
		mode: dual
		queryGroup: Dimensions
		source =
				let
				    Source = Snowflake.Databases("eileen.us-east-1.snowflakecomputing.com",SnowflakeWarehouse),
				    REPORTING_PROD_WH = Source{[Name="EDW_"&Environment,Kind="Database"]}[Data],
				    EDW_V_Schema = REPORTING_PROD_WH{[Name="EDW_V",Kind="Schema"]}[Data],
				    D_CHANNEL_View = EDW_V_Schema{[Name="D_CHANNEL",Kind="View"]}[Data],
				    #"Remove Underscores" = Table.TransformColumnNames(D_CHANNEL_View,  each Text.Replace( _, "_", " " ) ),
				    #"Renamed Columns" = Table.TransformColumnNames( #"Remove Underscores",  each Text.Proper( _ ) ),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Channel Active] <> "No")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Channel Key", "Channel Name", "Sub Channel Name", "Channel Format", "Channel Geography", "Channel Active"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "Finance Channel", each if [Channel Key] = 2020101 then "Digital" else if [Channel Key] = 2020201 then "Full Price US Stores" else if [Channel Key] = 2020202 then "Canada" else if [Channel Key] = 2030101 then "Renew Digital" else if [Channel Key] = 2030201 then "Renew Stores" else if [Channel Key] = 2040201 then "Company Stores" else if [Channel Key] = 1010202 then "WHOLESALE CANADA" else if [Channel Key] = 1010203 then "WHOLESALE INTERNATIONAL" else if [Channel Key] = 1010301 then "WHOLESALE US FULL PRICE" else if [Channel Key] = 1010201 then "WHOLESALE US SPECIALTY" else if [Channel Key] = 1010101 then "WHOLESALE 3RD PARTY" else "N/A"),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Sort", each if [Channel Key] = 2020101 then 1 else if [Channel Key] = 2020201 then 2 else if [Channel Key] = 2040201 then 3 else if [Channel Key] = 2020202 then 4 else if [Channel Key] = 2030201 then 5 else if [Channel Key] = 2030101 then 6 else if [Channel Key] = 1010301 then 7 else if [Channel Key] = 1010201 then 8 else if [Channel Key] = 1010101 then 9 else if [Channel Key] = 1010202 then 10 else if [Channel Key] = 1010203 then 11 else null),
				    #"Added Conditional Column2" = Table.AddColumn(#"Added Conditional Column1", "Finance Channel (Product Dashboard)", each if [Channel Key] = 2020202 then "Canada" else if [Channel Key] = 2020101 then "Digital" else if [Channel Key] = 2020201 then "US Stores" else if [Channel Key] = 1010101 then "eCommerce" else if [Channel Key] = 1010201 then "Stores" else if [Channel Key] = 2030101 then "Renew Digital" else if [Channel Key] = 2030201 then "Renew Stores" else if [Channel Key] = 2040201 then "Company Stores" else "Exclude"),
				#"Added Conditional Column3" = Table.AddColumn(#"Added Conditional Column2", "Finance Channel (Product Dashboard) Sort", each if [Channel Key] = 2020202 then 4 else if [Channel Key] = 2020101 then 1 else if [Channel Key] = 2020201 then 2 else if [Channel Key] = 1010101 then 9 else if [Channel Key] = 1010201 then 8 else if [Channel Key] = 2030101 then 6 else if [Channel Key] = 2030201 then 5 else if [Channel Key] = 2040201 then 3 else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column3",{{"Sort", Int64.Type},{"Finance Channel (Product Dashboard) Sort", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

