table ExecutiveDashboard_SubDomain
	lineageTag: 14a6f274-01b0-4c21-97a8-ce475af4d82d

	column REPORT_NAME
		dataType: string
		lineageTag: 13b03744-ce4c-492e-ae5f-d12ffa7ced04
		summarizeBy: none
		sourceColumn: REPORT_NAME

		annotation SummarizationSetBy = Automatic

	column LAKEHOUSE_TABLE_NAME
		dataType: string
		lineageTag: 1059c8fd-aace-456c-a2ca-2dcef0d24b50
		summarizeBy: none
		sourceColumn: LAKEHOUSE_TABLE_NAME

		annotation SummarizationSetBy = Automatic

	column SNOWFLAKE_VIEW_TABLE_NAME
		dataType: string
		lineageTag: 8f842007-8c42-414f-a713-74ceb5d12fbc
		summarizeBy: none
		sourceColumn: SNOWFLAKE_VIEW_TABLE_NAME

		annotation SummarizationSetBy = Automatic

	column SNOWFLAKE_TABLE_NAME2
		dataType: string
		lineageTag: fefc85c8-b97e-4b88-8019-8b414a91ba47
		summarizeBy: none
		sourceColumn: SNOWFLAKE_TABLE_NAME2

		annotation SummarizationSetBy = Automatic

	partition ExecutiveDashboard_SubDomain = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\EileenFisher\dev\readiness\ExecutiveDashboard_SubDomain.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"REPORT_NAME", type text}, {"LAKEHOUSE_TABLE_NAME", type text}, {"SNOWFLAKE_VIEW_TABLE_NAME", type text}, {"SNOWFLAKE_TABLE_NAME2", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

