table 'Header-Sales Flash'
	lineageTag: c62a37c2-ae5a-47d9-ab24-c268176e05fa

	column Period
		dataType: string
		lineageTag: 9a86f03f-a788-436b-a2d1-e855c6257952
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: 'Period Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Period Sort'
		dataType: int64
		formatString: 0
		lineageTag: f2d8194f-0c4d-406e-8afd-12c1b2205d91
		summarizeBy: sum
		sourceColumn: Period Sort

		annotation SummarizationSetBy = Automatic

	partition 'Header-Sales Flash' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCg9xUdJRMlSK1YlW8gWzjcDsSDDbWCk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, #"Period Sort" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type text}, {"Period Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

