table 'Headers - Executive Summary'
	lineageTag: ac49e7cc-3b8f-48fc-920f-1406b0082269

	column Period
		dataType: string
		lineageTag: 65b1382a-2da1-47ad-86d4-0254e6cb7637
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: 'Period Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Business Unit'
		dataType: string
		lineageTag: 9a6a2ad5-713d-43bc-89a8-3bdfbf6ad861
		summarizeBy: none
		sourceColumn: Business Unit
		sortByColumn: 'Business Unit Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Period Sort'
		dataType: int64
		formatString: 0
		lineageTag: 65e58a08-0387-486a-9513-d6659718daef
		summarizeBy: sum
		sourceColumn: Period Sort

		annotation SummarizationSetBy = Automatic

	column 'Business Unit Sort'
		dataType: int64
		formatString: 0
		lineageTag: 63b53622-fefc-43a5-a1ed-733154f046a0
		summarizeBy: sum
		sourceColumn: Business Unit Sort

		annotation SummarizationSetBy = Automatic

	column 'Period Abbrv'
		dataType: string
		lineageTag: 59988060-7f0c-47a3-a3d5-4f38133ddd02
		summarizeBy: none
		sourceColumn: Period Abbrv
		sortByColumn: 'Period Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Business Unit IMU'
		dataType: string
		lineageTag: 9bfc31c0-2ce4-4fcb-8788-04f1bac68298
		summarizeBy: none
		sourceColumn: Business Unit IMU

		annotation SummarizationSetBy = Automatic

	partition 'Headers - Executive Summary' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fc+7CoMwFIDhVwmZXUzyBNXVpQ2IBIdQD1VqTbDp0LdvQCmH3IYccvuGXynaAzyJM6TVDmhFe9n62crGz9ovdpzIFe6wWEfHStHObG5GpkOGZcwAekdkQIRnyOUzPcD5h//m+C8y/5Ml/WxWeOsVzh6O78htXqyFqVCFPSv6ZCHmvMjjWmxF0SbLpXF6JY15Wb19z/o6us+Xh55lfbI85DzL4/LQirQdfw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, #"Period Abbrv" = _t, #"Business Unit" = _t, #"Period Sort" = _t, #"Business Unit Sort" = _t, #"Business Unit IMU" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type text}, {"Business Unit", type text}, {"Period Sort", Int64.Type}, {"Business Unit Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

