table 'Allocated Channel (DTC)'
	lineageTag: b3982e67-e3d2-4d5e-b101-0856fab1d4fd

	column 'Channel Key'
		dataType: double
		isHidden
		isNullable: false
		sourceProviderType: decimal(38, 0)
		lineageTag: f6e554b3-abcb-4e8a-b783-e53528410d70
		summarizeBy: none
		sourceColumn: Channel Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Allocated Channel Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 3003067d-2e85-4220-bf5e-f7500d93bb6f
		summarizeBy: none
		sourceColumn: Allocated Channel Name

		annotation SummarizationSetBy = Automatic

	column 'Allocated Sub Channel Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 5a24f415-0169-47d5-96fc-ab0d337889c3
		summarizeBy: none
		sourceColumn: Allocated Sub Channel Name

		annotation SummarizationSetBy = Automatic

	column 'Allocated Channel Format'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: b2f321b3-ceb6-4ca6-94fc-7d5a93e1842f
		summarizeBy: none
		sourceColumn: Allocated Channel Format

		annotation SummarizationSetBy = Automatic

	column 'Allocated Channel Geography'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 6f60df24-57d4-488b-97e7-a44c8f2af1f9
		summarizeBy: none
		sourceColumn: Allocated Channel Geography

		annotation SummarizationSetBy = Automatic

	column 'Channel Active'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: c5df3137-0142-4123-ba60-89fccea8d6df
		summarizeBy: none
		sourceColumn: Channel Active

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 12ed1757-33d2-400d-bec4-174c19a0f863
		summarizeBy: none
		sourceColumn: Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Allocated Finance Channel'
		dataType: string
		lineageTag: ca30ec51-6942-41dc-aefc-670c54f5e080
		summarizeBy: none
		sourceColumn: Allocated Finance Channel

		annotation SummarizationSetBy = Automatic

	partition 'Allocated Channel (DTC)' = m
		mode: dual
		queryGroup: Dimensions
		source =
				let
				    Source = Snowflake.Databases("eileen.us-east-1.snowflakecomputing.com",SnowflakeWarehouse),
				    REPORTING_PROD_WH = Source{[Name="EDW_"&Environment,Kind="Database"]}[Data],
				    EDW_V_Schema = REPORTING_PROD_WH{[Name="EDW_V",Kind="Schema"]}[Data],
				    D_CHANNEL_View = EDW_V_Schema{[Name="D_CHANNEL",Kind="View"]}[Data],
				    #"Remove Underscores" = Table.TransformColumnNames(D_CHANNEL_View,  each Text.Replace( _, "_", " " ) ),
				    #"Renamed Columns" = Table.TransformColumnNames( #"Remove Underscores",  each Text.Proper( _ ) ),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Channel Active] <> "No")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Channel Closure Date"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"Channel Key", "Channel Name", "Sub Channel Name", "Channel Format", "Channel Geography", "Channel Active"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "Allocated Finance Channel", each if [Channel Key] = 2020101 then "Digital" else if [Channel Key] = 2020201 then "Full Price US Stores" else if [Channel Key] = 2020202 then "Canada" else if [Channel Key] = 2030101 then "Renew Digital" else if [Channel Key] = 2030201 then "Renew Stores" else if [Channel Key] = 2040201 then "Company Stores" else if [Channel Key] = 1010202 then "WHOLESALE CANADA" else if [Channel Key] = 1010203 then "WHOLESALE INTERNATIONAL" else if [Channel Key] = 1010301 then "WHOLESALE US FULL PRICE" else if [Channel Key] = 1010201 then "WHOLESALE US SPECIALTY" else if [Channel Key] = 1010101 then "WHOLESALE 3RD PARTY" else "N/A"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Conditional Column",{{"Channel Format", "Allocated Channel Format"}, {"Channel Geography", "Allocated Channel Geography"}, {"Channel Name", "Allocated Channel Name"}, {"Sub Channel Name", "Allocated Sub Channel Name"}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns1", "Sort", each if [Channel Key] = 2020101 then 1 else if [Channel Key] = 2020201 then 2 else if [Channel Key] = 2040201 then 3 else if [Channel Key] = 2020202 then 4 else if [Channel Key] = 2030201 then 5 else if [Channel Key] = 2030101 then 6 else if [Channel Key] = 1010301 then 7 else if [Channel Key] = 1010201 then 8 else if [Channel Key] = 1010101 then 9 else if [Channel Key] = 1010202 then 10 else if [Channel Key] = 1010203 then 11 else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

