table 'Budget (Inventory)'
	lineageTag: a25bbec1-0708-4081-a68f-1b6b90a5d59e

	measure 'Inventory Budget (Sum)' =
			
			if(
			    SELECTEDVALUE('Currency Selector'[Currency Selection])="Local",
			    SUM('Budget (Inventory)'[Inventory Budget Value]),
			    IF (
			        HASONEVALUE ( 'Currency Selector'[Currency Selection] ),
			            SUMX (
			                'Budget (Inventory)',
			                'Budget (Inventory)'[Inventory Budget Value]*LOOKUPVALUE('Currency Pivot'[Conversion Value],'Currency Pivot'[Currency Key],'Budget (Inventory)'[Currency Key])
			                )
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cbdc248f-0293-4915-87a6-d12c37256352

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Category
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 9e7b3e71-1b4b-4370-b744-9150054696a9
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: bc94fc4e-2a79-4ac4-a377-2de21fe0e80e
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 35adf0d4-01a7-42da-bb53-a0eab9e3b381
		summarizeBy: none
		sourceColumn: Date Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Inventory Budget Value'
		dataType: double
		isHidden
		formatString: \$#,0;(\$#,0);\$#,0
		sourceProviderType: decimal(38, 15)
		lineageTag: 9febe6cf-d5e6-4592-8039-d2de10eb83d4
		summarizeBy: sum
		sourceColumn: Inventory Budget Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Currency Code'
		dataType: string
		isHidden
		sourceProviderType: nvarchar(3)
		lineageTag: e5116bfb-12ad-4884-b477-f6317034fe8e
		summarizeBy: none
		sourceColumn: Currency Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Currency Key'
		dataType: double
		isHidden
		formatString: 0
		sourceProviderType: decimal(38, 0)
		lineageTag: e20437b1-c32e-409f-9c04-3c600832baa8
		summarizeBy: none
		sourceColumn: Currency Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Budget (Inventory)' = m
		mode: directQuery
		queryGroup: Facts
		source = ```
				let
				    Source = Snowflake.Databases("eileen.us-east-1.snowflakecomputing.com",SnowflakeWarehouse),
				    EDW_PROD_Database = Source{[Name="EDW_"&Environment,Kind="Database"]}[Data],
				    SQLStatement = 
				    "
				select T.*,
				from EDW_V.F_INVENTORY_BUDGET T
				where MONTH_BEGIN_DATE  >= datefromparts(year(getdate()) - 3, 1, 1)
				    ",
				NativeQuery = Value.NativeQuery(EDW_PROD_Database, SQLStatement, null, [EnableFolding=true]),
				    #"Remove Underscores" = Table.TransformColumnNames(NativeQuery,  each Text.Replace( _, "_", " " ) ),
				    #"Renamed Columns" = Table.TransformColumnNames( #"Remove Underscores",  each Text.Proper( _ ) ),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"Category", "Subcategory", "Date Key", "Inventory Budget Value", "Currency Code", "Currency Key"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Date Key", Int32.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

