table Delivery
	lineageTag: 0a679b90-0d3d-49fb-a89a-9cbe331433d1

	column 'Delivery Code Key'
		dataType: int64
		isHidden
		sourceProviderType: int
		lineageTag: bff61bf2-f5ff-44cd-a756-21a9ce9244aa
		summarizeBy: count
		sourceColumn: Delivery Code Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Delivery Code'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: da51fe0d-2485-40e5-9dba-419c49935f32
		summarizeBy: none
		sourceColumn: Delivery Code

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		sourceProviderType: nvarchar(60)
		lineageTag: c3648b10-3864-44aa-b356-351c7d2a2ea2
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column 'Color Code'
		dataType: string
		sourceProviderType: nvarchar(10)
		lineageTag: 3e0e8a69-6272-44a0-9f72-1e04bf038035
		summarizeBy: none
		sourceColumn: Color Code

		annotation SummarizationSetBy = Automatic

	column 'Account Code'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: d2d710f0-45c8-437a-8fcb-acd08a5cc6ba
		summarizeBy: none
		sourceColumn: Account Code

		annotation SummarizationSetBy = Automatic

	column 'Style Color Collection'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: e4eda693-e75a-4bc8-94ee-fee0b2efb145
		summarizeBy: none
		sourceColumn: Style Color Collection

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: a93941e0-ac8c-4430-b40b-557516338548
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	column 'Delivery Name'
		dataType: string
		sourceProviderType: nvarchar(10)
		lineageTag: 61c8cea8-1c97-4c4c-8c8b-e9f91fc457e5
		summarizeBy: none
		sourceColumn: Delivery Name

		annotation SummarizationSetBy = Automatic

	column 'Style Prefix'
		dataType: string
		sourceProviderType: nvarchar(10)
		lineageTag: 0ad48f68-ac12-4c6c-975d-7c9c96fa633b
		summarizeBy: none
		sourceColumn: Style Prefix

		annotation SummarizationSetBy = Automatic

	column 'Delivery Year'
		dataType: string
		sourceProviderType: nvarchar(10)
		lineageTag: 686592bf-8294-4710-9f35-1fcfd4f2e04f
		summarizeBy: none
		sourceColumn: Delivery Year

		annotation SummarizationSetBy = Automatic

	column 'Delivery Month'
		dataType: string
		sourceProviderType: nvarchar(10)
		lineageTag: 1c647210-bb80-404f-83f3-f3808ffa8164
		summarizeBy: none
		sourceColumn: Delivery Month
		sortByColumn: 'Month Sort'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dtc Transactions Start Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: a0b64599-77b7-48ff-bca7-a67b7bf84d42
		summarizeBy: none
		sourceColumn: Dtc Transactions Start Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Key'
		dataType: int64
		isHidden
		sourceProviderType: int
		lineageTag: 4a79bff1-716d-4bee-81b9-86b7dd48899f
		summarizeBy: none
		sourceColumn: Delivery Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Wholesale Account Key'
		dataType: int64
		isHidden
		sourceProviderType: int
		lineageTag: 27651e46-bf0e-4532-97af-62a457d9fbf4
		summarizeBy: count
		sourceColumn: Wholesale Account Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Exclusive
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: ee3b03e1-0584-4eaf-a807-1a6f3d8a9fda
		summarizeBy: none
		sourceColumn: Exclusive

		annotation SummarizationSetBy = Automatic

	column 'Effective Dtc Transactions Start Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 8acc8ec2-65a6-4fc1-8d0e-6d83cd9a7f72
		summarizeBy: none
		sourceColumn: Effective Dtc Transactions Start Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Effective Dtc Transactions End Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: c1b85e1b-a059-4927-920f-1bc15c4a51aa
		summarizeBy: none
		sourceColumn: Effective Dtc Transactions End Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Sort'
		dataType: int64
		isHidden
		sourceProviderType: int
		lineageTag: 115281a5-4078-40ae-94d6-68a5e22f05c9
		summarizeBy: sum
		sourceColumn: Month Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Season
		dataType: string
		sourceProviderType: nvarchar(16777216)
		lineageTag: 8ce54725-36ac-4d80-bbbd-c2410ac8087c
		summarizeBy: none
		sourceColumn: Season
		sortByColumn: 'Season Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Season Sort'
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 7221f0b3-1abf-4697-8962-daae0070c5cd
		summarizeBy: sum
		sourceColumn: Season Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Delivery = m
		mode: dual
		queryGroup: Dimensions
		source = ```
				let
				    Source = Snowflake.Databases("eileen.us-east-1.snowflakecomputing.com", SnowflakeWarehouse),
				    EDW_PROD_Database = Source{[Name="EDW_" & Environment, Kind="Database"]}[Data],
				    SQLStatement = 
				    "
				    SELECT D.*, 
				    CASE 
				        WHEN D.DELIVERY_MONTH='Jan' THEN 1
				        WHEN D.DELIVERY_MONTH='Feb' THEN 2
				        WHEN D.DELIVERY_MONTH='Mar' THEN 3
				        WHEN D.DELIVERY_MONTH='Apr' THEN 4
				        WHEN D.DELIVERY_MONTH='May' THEN 5
				        WHEN D.DELIVERY_MONTH='Jun' THEN 6
				        WHEN D.DELIVERY_MONTH='Jul' THEN 7
				        WHEN D.DELIVERY_MONTH='Aug' THEN 8
				        WHEN D.DELIVERY_MONTH='Sep' THEN 9
				        WHEN D.DELIVERY_MONTH='Oct' THEN 10
				        WHEN D.DELIVERY_MONTH='Nov' THEN 11
				        WHEN D.DELIVERY_MONTH='Dec' THEN 12
				    END AS MONTH_SORT,
				    CASE 
				        WHEN MONTH_SORT<7 THEN CONCAT('SPRING ',D.DELIVERY_YEAR)
				        WHEN MONTH_SORT>6 THEN CONCAT('FALL ',D.DELIVERY_YEAR)
				    END AS SEASON,
				    CASE
				        WHEN MONTH_SORT<7 THEN CONCAT(D.DELIVERY_YEAR,1)
				        WHEN MONTH_SORT>6 THEN CONCAT(D.DELIVERY_YEAR,2)
				    END AS SEASON_SORT
				    FROM EDW_PROD.EDW_V.V_DELIVERY D
				    ",
				    NativeQuery = Value.NativeQuery(EDW_PROD_Database, SQLStatement, null, [EnableFolding=true]),
				    #"Remove Underscores" = Table.TransformColumnNames(NativeQuery, each Text.Replace(_, "_", " ")),
				    #"Renamed Columns" = Table.TransformColumnNames(#"Remove Underscores", each Text.Proper(_)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Delivery Key", Int32.Type}, {"Delivery Code Key", Int32.Type}, {"Wholesale Account Key", Int32.Type}, {"Month Sort", Int32.Type}, {"Season Sort", Int32.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

