table 'Order Type Join'
	isHidden
	lineageTag: 43dd44c9-66e4-40cd-9fc4-622bda6f92b5

	column 'Order Type'
		dataType: string
		isHidden
		lineageTag: cbe5dab4-c728-46f7-b584-629fcccbf130
		summarizeBy: none
		sourceColumn: Order Type
		sortByColumn: 'Order Type Sort'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Order Type Sort'
		dataType: string
		isHidden
		lineageTag: 46afa8ed-d499-4dc7-98cc-89a972e2cb8f
		summarizeBy: none
		sourceColumn: Order Type Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Order Type Join' = m
		mode: import
		queryGroup: 'Join Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMg5yUQhwDAqJVNJRMlWK1YlWcgnyD1AI9vAMAIqYgEXcHIFcfz8FTz/PEE9Hn2CghCGKRJCrf5CLaxBQ3AgsHghiGivFxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Order Type" = _t, #"Order Type Sort" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Order Type", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

