table 'Original Channel (DTC)'
	lineageTag: 2d0e8a24-181e-4ed8-be70-4ae524f235d2

	column 'Channel Key'
		dataType: double
		isHidden
		isNullable: false
		sourceProviderType: decimal(38, 0)
		lineageTag: 5102e980-db4a-43f5-9044-25d12481a6da
		summarizeBy: none
		sourceColumn: Channel Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Channel Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 9be3ae1e-1811-4f94-884b-3e5ec823d018
		summarizeBy: none
		sourceColumn: Original Channel Name

		annotation SummarizationSetBy = Automatic

	column 'Original Sub Channel Name'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: bd06888a-98ed-449d-9668-2cd68d2a5890
		summarizeBy: none
		sourceColumn: Original Sub Channel Name

		annotation SummarizationSetBy = Automatic

	column 'Original Channel Format'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 2e98dbbe-57bf-4205-843e-c032e8ba703d
		summarizeBy: none
		sourceColumn: Original Channel Format

		annotation SummarizationSetBy = Automatic

	column 'Original Channel Geography'
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 53347a10-0d42-4b31-8352-6b863c412078
		summarizeBy: none
		sourceColumn: Original Channel Geography

		annotation SummarizationSetBy = Automatic

	column 'Channel Active'
		dataType: string
		isHidden
		isNullable: false
		sourceProviderType: nvarchar(100)
		lineageTag: 0f981a07-eb4a-4921-af25-a49ef165d455
		summarizeBy: none
		sourceColumn: Channel Active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Original Finance Channel'
		dataType: string
		lineageTag: 25939a64-e3eb-45dd-b6f0-6dda7deccfc9
		summarizeBy: none
		sourceColumn: Original Finance Channel
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3de9e5c7-96a2-4a17-be26-ab24a98db80a
		summarizeBy: sum
		sourceColumn: Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Original Channel (DTC)' = m
		mode: dual
		queryGroup: Dimensions
		source =
				let
				    Source = Snowflake.Databases("eileen.us-east-1.snowflakecomputing.com",SnowflakeWarehouse),
				    REPORTING_PROD_WH = Source{[Name="EDW_"&Environment,Kind="Database"]}[Data],
				    EDW_V_Schema = REPORTING_PROD_WH{[Name="EDW_V",Kind="Schema"]}[Data],
				    D_CHANNEL_View = EDW_V_Schema{[Name="D_CHANNEL",Kind="View"]}[Data],
				    #"Remove Underscores" = Table.TransformColumnNames(D_CHANNEL_View,  each Text.Replace( _, "_", " " ) ),
				    #"Renamed Columns" = Table.TransformColumnNames( #"Remove Underscores",  each Text.Proper( _ ) ),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Channel Active] <> "No")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Channel Closure Date"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"Channel Key", "Channel Name", "Sub Channel Name", "Channel Format", "Channel Geography", "Channel Active"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "Original Finance Channel", each if [Channel Key] = 2020101 then "Digital" else if [Channel Key] = 2020201 then "Full Price US Stores" else if [Channel Key] = 2020202 then "Canada" else if [Channel Key] = 2030101 then "Renew Digital" else if [Channel Key] = 2030201 then "Renew Stores" else if [Channel Key] = 2040201 then "Company Stores" else if [Channel Key] = 1010202 then "WHOLESALE CANADA" else if [Channel Key] = 1010203 then "WHOLESALE INTERNATIONAL" else if [Channel Key] = 1010301 then "WHOLESALE US FULL PRICE" else if [Channel Key] = 1010201 then "WHOLESALE US SPECIALTY" else if [Channel Key] = 1010101 then "WHOLESALE 3RD PARTY" else "N/A"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Conditional Column",{{"Channel Format", "Original Channel Format"}, {"Channel Geography", "Original Channel Geography"}, {"Channel Name", "Original Channel Name"}, {"Sub Channel Name", "Original Sub Channel Name"}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Renamed Columns1", "Sort", each if [Channel Key] = 2020101 then 1 else if [Channel Key] = 2020201 then 2 else if [Channel Key] = 2040201 then 3 else if [Channel Key] = 2020202 then 4 else if [Channel Key] = 2030201 then 5 else if [Channel Key] = 2030101 then 6 else if [Channel Key] = 1010301 then 7 else if [Channel Key] = 1010201 then 8 else if [Channel Key] = 1010101 then 9 else if [Channel Key] = 1010202 then 10 else if [Channel Key] = 1010203 then 11 else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

